### ISSUE TITLE
Few HTML attributes are ignored

### ISSUE THREAD

**Issue by gkn06** [luwes/sinuous#106]
In the example below, attributes like **for, value** and **readonly** are ignored.
Am i doing wrong ? Can you help me to fix this ?

```
import { html } from "sinuous";

const INPUT = () => {
  return html`
    <label for="country">Country:</label>
    <input
      type="text"
      id="country"
      name="country"
      value="Norway"
      readonly
    /><br />
  `;
};

document.body.appendChild(INPUT());
```

**Comment by luwes** [comment]
@gkn06 thanks for the question. 

Sinuous uses properties instead of attributes to configure the element,
there's only a few convenience attribute names that are supported; class, and the data- and aria- attribute names.

in your case `for` should be `htmlFor`, `value` works I believe, `readonly` is a special one that doesn't have a property so the way Sinuous solves this without keeping a large special attribute name list is by providing a property `attrs` that can be set which will be used to set element attributes instead of properties.

I've put together a codesandbox with the fixes in your example
https://codesandbox.io/s/nifty-euler-nnkzr?file=/src/index.js:0-321

hope this helps and thanks for using Sinuous! 

```js
import { html } from "sinuous";

const INPUT = () => {
  return html`
    <label htmlFor="country">Country:</label>
    <input
      type="text"
      id="country"
      name="country"
      value="Norwayy"
      attrs=${{ readonly: "" }}
    /><br />
  `;
};

document.body.appendChild(INPUT());
```

**Comment by gkn06** [comment]
@luwes thanks a lot 😊 
 `value` works but I can't see it in devtools.
Between **readOnly** with camelcase works.

Thanks again for the awesome library. Really enjoying it
