### ISSUE TITLE
[documentation] There is no documentation about some of exposed api in sinuous!

### ISSUE THREAD

**Issue by samadadi** [luwes/sinuous#116]
Hi. I am using sinuous cdn link to build a simple app. When I log the sinuous object to console I see some functions that exposed to user but I can't find any documentation about those neither in sinuous website or in github page. Those are {S, api, cleanup, context, hs, on, root, sample, svg, tansaction}.

**Comment by heyheyhello** [comment]
There's not actually a lot of source code if you're wanting to learn how it works :) The core is sinuous/src, sinuous/h, and sinuous/observable.

The `S, cleanup, on, root, sample, transaction` are in sinuous/observable and are documented in the readme.md https://github.com/luwes/sinuous/tree/master/packages/sinuous/observable

The other functions, `h`/`html` and `hs`/`svg` are renderers from sinuous/src. Unless you use JSX or are working on Sinuous internals you don't need `h` or `hs`. There's an open PR to remove `context` (since it reduces bundle size to not have it).

The `api` is specifically sinuous/h's internal API. Here's my fork that has a bunch of JSDoc comments explaining it's internals: https://github.com/heyheyhello/sinuous/blob/types-api/packages/sinuous/h/src/api.js

**Comment by samadadi** [comment]
Thank you. This is such a nice library.

**Comment by luwes** [comment]
thanks for your feedback @samadadi, glad you like the library!

there is indeed some need for more extensive docs. @heyheyhello is right, the code is very small and not that complex if you like to check it out.

added a small section on the internal API today, 
https://github.com/luwes/sinuous#internal-api

closing the issue as the methods you mention do have some docs at https://github.com/luwes/sinuous/tree/master/packages/sinuous/observable though not very extensive.
