### ISSUE TITLE
Conditional rendering with no root element

### ISSUE THREAD

**Issue by pynnl** [luwes/sinuous#13]
#### Preproduce
 Template contains only conditional statement.

#### Expected
A `DocumentFragment` is returned with proper content based on the conditional block.

#### Actual
The conditional block is returned instead.

https://stackblitz.com/edit/js-y7ww82?file=index.js

**Comment by luwes** [comment]
Thanks for reporting, looking into these issues.

**Comment by pynnl** [comment]
Thanks. Sinuous does look really promising btw.

**Comment by luwes** [comment]
`map` was changed to return a `DocumentFragment` which made more sense actually, thanks for suggesting it!

I made a fork of your blitz here 
https://stackblitz.com/edit/sinuous-root?file=index.js

I'm not fully sure your first example would require code changes in the library because it can be easily written without the `html` tag which would just return the string in this case, or a node for example.

Do you have a case where removing the wrapping `html` tag would not work?

**Comment by pynnl** [comment]
In the first example, I used string just for fast demonstration. If it was a node, a function would still be returned instead of a `DocumentFragment`.
However, your patch somehow fixed that bug in the first example too 😅 . Thanks for quick response.
