### ISSUE TITLE
SVG <use> is not taking effect

### ISSUE THREAD

**Issue by kilgarenone** [luwes/sinuous#148]
I'm trying to use SVG sprites via `<use>` but it's not showing up:

**index.html**
```
<body>
    <svg xmlns="http://www.w3.org/2000/svg">
      <symbol id="add" viewBox="0 0 24 24">
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
    </svg>
  </body>
```
**app.js**
```
import {html, svg} from 'sinuous'
...
return html`${svg`<svg width="27" height="27"><use xlink:href="#add"></use></svg>`}`
```

**Comment by kilgarenone** [comment]
Reproduced in codesandbox: https://codesandbox.io/s/sinuous-hacker-news-forked-shh65

Am I missing something specific to Sinuous with respect to `<svg>` in particular?

**Comment by heyheyhello** [comment]
`xlink:href` is deprecated in favour of `href` https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

```js
return html`${svg`<svg width="27" height="27"><use href="#add"></use></svg>`}`
```

Works in the codesandbox. If you're curious, the issue is that Sinuous sets attributes via `el[name] = value` but `xlink:href` can't be set that way - it needs `el.setAttributeNS('http://www.w3.org/1999/xlink', 'href', '#add');`. Hopefully you can see why that's not worth supporting...

**Comment by kilgarenone** [comment]
Oh wow I didn't know that. Perfect. Thank you for the response ❤️
