### ISSUE TITLE
Why two foreach loops and seemingly unnecessary check?

### ISSUE THREAD

**Issue by quixot1c** [luwes/sinuous#161]
Running through your `observable` code so I could better debug my own code, I ran into something I found strange. It probably does make sense when considering side effects (as in many cases I found strange looking code which needed to be so because of side effects), but I cannot find a reason for this code to be the way it is here in this instance:

https://github.com/luwes/sinuous/blob/ece2c65c19939ec5742f999cfba6c83295c58118/packages/sinuous/observable/src/observable.js#L108

```javascript
    data._runObservers.forEach(observer => (observer._fresh = false)); // why do this in a seperate forEach?
    data._runObservers.forEach(observer => {
      if (!observer._fresh) observer(); // why check if false? should all be false?
    });
```
It seems this could all be done in a single `forEach()` and omitting the `!observer._fresh` check entirely. Or is there some magic going on between the first and last `forEach()`? Which would overturn my understanding of JavaScript completely ;)

**Comment by heyheyhello** [comment]
All observers are marked as stale, then, each observer is called one by one. **When an observer is called, it may also call child observers** which means one iteration of the loop may result in multiple observers being marked as fresh (meaning they've rerun and don't need to run again). If this was one for loop rather than two, then observers would run multiple times unnecessarily because each next iteration would blindly mark an observable as stale even if it had just ran.

It's kind of related to why the Set() is duplicated into a new runObservers - calling an observer can add values to the Set, so you'll get an infinite loop if you loop in place.

Great question tho! It did leave me confused when I was first debugging it.

**Comment by quixot1c** [comment]
Ah yes! Another side effect I missed 😅 Thanks for the clarification.
