### ISSUE TITLE
Observable optimizations

### ISSUE THREAD

**Issue by luwes** [luwes/sinuous#20]
- Using linear search[1] when removing edges
@localvoid mentioned this could be optimized.

https://github.com/luwes/sinuous/blob/e33c5e8bcdb461be61f7d078ac5e606b4745382a/packages/sinuous/observable/src/observable.js#L161

- Try out prevention of duplicate edges concept
https://github.com/ryansolid/solid/issues/46#issuecomment-515763043

**Comment by localvoid** [comment]
Also, instead of using `splice()` to remove edges, it is better to swap it with the latest element and use `pop()`. Order of edges in this array doesn't matter, so instead of triggering a copy of all elements after the one you are removing, it is better to swap it and remove the latest one.

**Comment by luwes** [comment]
@localvoid looks like the order might be needed. I tested pop() with swap but one test didn't pass with this change.

```js
function _unsubscribe(update) {
  update._children.forEach(_unsubscribe);
  update._observables.forEach(o => {
    const last = o._listeners[o._listeners.length-1];
    o._listeners[o._listeners.indexOf(update)] = last;
    o._listeners.pop();
  });
  update._cleanups.forEach(c => c());
  resetUpdate(update);
}
```

Test that didn't pass was this one:

https://github.com/luwes/sinuous/blob/7c2b1399baac0b03d61cd2e4f738378f1ba49fd0/packages/sinuous/observable/test/S.js#L161-L193

<img width="570" alt="Screen Shot 2019-08-03 at 3 23 46 PM" src="https://user-images.githubusercontent.com/360826/62416087-b686fb00-b602-11e9-869a-913fb2a5b73a.png">

**Comment by localvoid** [comment]
I thought that you are using push-pull strategy like in MobX/Vue with correct ordering. And it is actually important to switch to this strategy, so that you can always guarantee correct ordering and support lazy computation nodes (computed in MobX). The basic idea is that when observable is changed, it doesn't execute side effects(autorun in MobX) immediately, it goes through the graph and marks all nodes that they should be checked. With this strategy it is also easy to implement batching (transactions in MobX) because when observable is changed, you just mark all nodes and can apply multiple mutations in a batch. Then you need to execute computations with side effects and start pulling data from observables and lazy computation nodes, I am not sure how other libraries implement priorities for side effects execution, I would've implemented it by assigning a depth property (previous depth + 1) to nested side effects and used an array ordered by depth to store arrays with side effects. In real applications there shouldn't be too much nesting, so this array will be small and it will be quite fast to iterate through it and execute all side effects with correct ordering.

**Comment by ryansolid** [comment]
@luwes For reference since it's pertinent here as it has everything to do with evaluation order. This is the most basic example that I was talking about: https://codesandbox.io/s/vigorous-cherry-vo79c. 

In this example, we are avoiding recalculation of the child component by storing the result of the condition in an intermediate the only updates when the resolved boolean value changes. I also tried this with nested roots, but S prevents premature disposal also causing this issue. The more complex scenario (with related but not directly dependent values) with roots can be seen here: https://codesandbox.io/s/objective-tdd-dif57. You will notice that even swapping the order of the setters in the freeze doesn't change the outcome. 

I solved these problems in one way but it cost me the steep price of 1.5kb minified across the board. From my perspective not fixing allowing this case to work properly would be essentially admitting my library was completely broken. Approaches like MobX are built to avoid this sort of issue. S clock representation allows efficient batching without a ton of forced reordering but its also why this is a consideration, on what I consider a super common use case.

It would be interesting to see if you can think of a way to approach this without taking such a size hit.

**Comment by luwes** [comment]
@ryansolid I tried dropping in Sinuous in the simple example and it worked?
(not sure yet what the example should do)

there is one change I had to make because Sinuous doesn't have the equivalent of `S.value`. maybe that's why it doesn't break.

at the time I thought `S.value` could be an abstraction made outside the lib, that's why I didn't add it.

**Comment by ryansolid** [comment]
Yeah the value part is key.. if you set the name to name2 before turning it off you rerun the component. That's what we are trying to avoid. If you change the bottom to:
```js
  console.log("ON");
  data("name");
  data("name2");
  console.log("OFF");
  data(undefined);
```
You will see "view Hi" console logged an additional time (and missing the last "view undefined" I think).
It outputs:
```
view undefined
nested 4
view Hi 
nested 5
view Hi 
nested 5
```

The ideal output should be:
```
view undefined
nested 4
view Hi 
nested 5
view undefined
```

I managed to write the code to prevent this in Sinuous and hit the issue. This isn't the only way to solve it but:

```js
import { observable, root, sample, S } from "./observable.js";

root(() => {
  const data = observable(null),
    cache = observable(sample(() => !!data())),
    child = data => {
      S(() => console.log("nested", data().length));
      return "Hi";
    };
  S(prev => {
    const d = !!data();
    if (d === prev) return prev;
    cache(d);
    return d;
  });
  const memo = S(() => (cache() ? child(data) : undefined));
  S(() => console.log("view", memo()));
  data("name");
  data("name2");
  data(null);
});
```

**Comment by luwes** [comment]
Isn't this expected? This computed `S(() => console.log("nested", data().length));` will always run when the `data()` observable is changed.

Better in this case is to remove the computed in the child function.

```js
    child = data => {
      console.log("nested", data().length);
      return "Hi";
    };
```

Because the `memo` function renders the child already if `cache()` is `true`.

**Comment by ryansolid** [comment]
`nested ${data().length}` should run when data changes except if that change would lead to that branch not existing anymore.  It isn't that nested shouldn't be a computation. It's that you don't want to rerun the whole Child component again. Pretend Child has some expensive operation, maybe some async data load and you cannot just create it ahead of time and hoist it. The scenario I'm trying to simulate is a variation on:
```jsx
<div>{ data() !== null && <ExpensiveChild data={data} /> }</div>
```
Obviously that would re-create everything time data changes. And in a Virtual DOM library that's fine or if you have something like Hooks. But in libraries like ours re-evaluating that Child can be extremely expensive. It doesn't just have to be Async.. what if it is a whole tree of DOM nodes, with their own bindings. You could be doing 100's of ms of work. 

If you look at the expected results in the example I provided about you see:
```
nested 4
nested 5
````
Each one exactly once, because you change the data to strings that length exactly once. The reason for the crash error is after that it tries to re-evaluate one more time and hits `nested ${undefined.length}` even though the conceptually the parent computation should never have let that branch evaluate again as it would be seen from the developer as being downstream. If you write:
```js
data() !== null && data().length
```
You would never expect `data().length` to be evaluated if `data() === null`. This issue is caused by S.value mind you since by breaking synchronicity in S the new value is only able to be set to pending state on first clock cycle, and by providing the intermediate it gets one more chance to re-evaluate. This isn't the only way to solve the issue. Nested roots and handling your own disposal also seems like it would work (it's what we do in list reconciliation). However, similarly, S holds the disposal of nested roots to the next cycle in a similar manner causing the exact same issue.

Ultimately the scenario I'm trying to display is one that there shouldn't be another `view ${rendered}`. Seeing the `view Hi` a 2nd time means that not only the Child computation is retriggered but the whole Child component was disposed and rerendered again. In that scenario the cache intermediate is pointless and you could literally just write a ternary and it would work. But this is what you'd effectively be doing.
```
1. Condition evoked, resolves to false, return undefined
> view undefined
2. Data is updated to 'name', Condition evoked, resolves to true, creates Child and Child computation
> nested 4
3. Return Child component children
> view Hi
4.  Data is updated to 'name2', Condition evoked, resolves to true, disposes of the previous iteration, creates Child and Child computation
> nested 5
5. Return Child component children
> view Hi
6.  Data is updated to null, Condition evoked, resolves to false, disposes of the previous iteration. Returns undefined
> view undefined
```

Whereas what the example is trying to achieve is:
```
1. Condition evoked, resolves to false, return undefined
> view undefined
2. Data is updated to 'name', Condition evoked, resolves to true, create Child and Child computation
> nested 4
3. Return component children
> view Hi
4.  Data is updated to 'name2', Condition evoked, resolves to true, still true no change. Update nested computation
> nested 5
5.  Data is updated to null, Condition evoked, resolves to false, disposes of the previous iteration. Returns undefined
> view undefined
```
I'm not saying this is the only way to solve this problem. I am just thinking that this is real so I wanted to bring it to your attention. All it takes is you have some branching that evaluates a condition that can resolve to the same boolean value under multiple input values like `count() > 5`. I first noticed this in the footer of the TodoMVC example which shows based on `todos().length`. In that case it is relatively inexpensive. Maybe the answer is hoisting:

You could always do this:
```jsx
const expensive = <ExpensiveChild data={data} />;
return <div>{ data() !== null && expensive }</div>
```
And if you are ok taking the expensive hit upfront (and possibly multiple times when it isn't even visible) and if you put adequate checks on the props on the inside of the Component you are in good shape. If that is sufficient maybe this isn't a consideration. In any case, I hope I've explained this adequately now, and you can make your own call.

**Comment by luwes** [comment]
thanks for explaining @ryansolid, this helps a lot. I understand now.
I'm gonna look into it, try to set up a test for this case.

**Comment by luwes** [comment]
after looking again, I'm a bit surprised that this parent computation doesn't unsubscribe the child computation before running 🤔 

parent: `const memo = S(() => (cache() ? child(data) : undefined));`
child: `S(() => console.log("nested", data().length));`

**Comment by luwes** [comment]
aah because `cache()` prevents `memo` from running

**Comment by luwes** [comment]
first attempt that comes to mind is to go up the tree and verify if the parents have actually run before the children computations, if not don't run the child.

**Comment by ryansolid** [comment]
This is what I ended up with in Solid, but it required significant changes: https://codesandbox.io/s/frosty-hooks-8vheh

I added the ability to provide a comparer function just like S.value on computations as well (I call them memos). 

To be fair this is the simple case we are looking at right now. The more complex case is if there are 2 observables being set at the same time and one is read from the conditional and one is read from the child. But even though there isn't a direct dependency you still wouldn't expect the other path to run. Like:

```js
//initial
data = S.data('name')
count = S.data(4)

//condition
count() > 0 && data().length

//set frozen/transaction
freeze(() => {
  data(null);
  count(0);
})
```
(Pretend all the proper intermediate values/nested roots are in place). In this scenario with S the order of the setters matters too, so it's possible if ordered that way setting data to `null` before setting `count` to 0 actually causes this error as well, even though all computations see the proper values. Basically depending on the transaction strategy even if there are no invalid data states ie.. data will never be null when count is still 4 it doesn't guarantee the order since the condition and the nested computations are not dependent on the same data. 

In case S.js never solved these sort of issues(subclocks are what Adam is working on) but MobX does. Surplus functions fine enough without worrying about this, but it was a sticking point for me.

**Comment by luwes** [comment]
@ryansolid I found a solution that passed your initial test case, it just adds 70 bytes to Sinuous observable so far. Performance wise it might not be the best, it uses some more linear `indexOf` checks.

https://github.com/luwes/sinuous/commit/f84e5e8e17e0340773a58fd459b6f9f44d192c75#diff-1b79690b5af7074f510bbba8f138989dR91

Also not sure if it is good for every edge case. If you have more test cases please let me know. Good you brought this issue up again because it does feel more to a bug than a feature.

**Comment by ryansolid** [comment]
Interesting, I did something similar in terms of delaying execution but I was using heuristics that I got from a different technique. It does give me hope there is a simple general solution.

**Comment by luwes** [comment]
actually there is still something wrong, I added a `child2` which made the test pass somehow.

**Comment by luwes** [comment]
got it working again. the solution is 2 part. one for cleaning up already run computations and the other marks the child computations fresh if they were removed in the parent letting them skip any scheduled updates.

```js
    // If any children computations were removed mark them as fresh.
    prevChildren.forEach(u => {
      if (update._children.indexOf(u) === -1) {
        u._fresh = 1;
      }
    });

    // If any children were marked as fresh remove them from the run lists.
    const allChildren = getChildrenDeep(update._children, []);
    allChildren.forEach(u => {
      if (u._fresh) {
        u._observables.forEach(o => {
          o._runListeners.splice(o._runListeners.indexOf(u), 1);
        });
      }
    });
```

**Comment by luwes** [comment]
for reference this article helped a lot with forming the solutions, starting at `Running computations`.
https://medium.com/hackernoon/becoming-fully-reactive-an-in-depth-explanation-of-mobservable-55995262a254

**Comment by luwes** [comment]
I added some perf tests from Mobx
https://github.com/luwes/sinuous/blob/bfc5df8ef7e088fb8bb2fdb64fbc2eb3445e2a9f/packages/sinuous/observable/test/perf/perf.js

- `Observable with many observers + dispose` is taking about 20s compared to mobx 433ms (note that this is 100,000 subscriptions)
- `Late dependency change` is slow too. 380ms compared to mobx 84ms.

### Sinuous perf results

```
One observers many observes one - Started/Updated in 1/34 ms.
500 props observing sibling -  Started/Updated in 0/2 ms.
Late dependency change - Updated in 380ms.
Unused computables -   Updated in 23 ms.
Unused observables -  Updated in 17 ms.
Observable with many observers + dispose - after subscribe: 182ms, after set: 15645ms, total: 20494ms


Completed performance suite in 21.09 sec.
```

**Comment by ryansolid** [comment]
The more complicated scenario (two seemingly unrelated pieces of state) almost works but is missing the last `view undefined`. 

```js
root(() => {
  const data = observable(null),
    trigger = observable(false),
    cache = observable(sample(() => !!trigger())),
    child = data => {
      S(() => console.log("nested", data().length));
      return "Hi";
    };
  S(prev => {
    const d = !!data();
    if (d === prev) return prev;
    cache(d);
    return d;
  });
  const memo = S(() => (cache() ? child(data) : undefined));
  S(() => console.log("view", memo()));
  transaction(() => {
    trigger(true);
    data("name");
  });
  transaction(() => {
    trigger(true);
    data("name2");
  });
  transaction(() => {
    data(undefined);
    trigger(false);
  });
});
```
In any case its interesting. I wonder if the slow down is algorithmic, data structure, or just down to micro optimizations (for loop vs forEach).

**Comment by leeoniya** [comment]
@luwes would it be difficult to also assess the pef of cellx in your bench? it claims some pretty major perf wins over MobX: https://github.com/Riim/cellx#benchmark

**Comment by luwes** [comment]
@leeoniya interesting, I'll have a look at that lib for sure.

@ryansolid I think it might be data structure in this case what @localvoid was talking about. The very slow test is where one observable has 100,000 subscribers so when the observable value is set to a new value it first has to remove the listener like so 

```js
observable._listeners.splice(observable._listeners.indexOf(update), 1);
```

then it runs the derivation/computed and re-subscribes the listener.
it does this 100,000 times.

--- 

ah snap, I removed that check. good you reviewed again. I'll look into that issue of `view undefined`

**Comment by luwes** [comment]
@leeoniya Sinuous is slower but performs quite well in that list.

## Sinuous
<img width="515" alt="Screen Shot 2019-09-04 at 5 38 10 PM" src="https://user-images.githubusercontent.com/360826/64294185-396ddf00-cf3c-11e9-969e-637a09be8570.png">

## Cellx
<img width="561" alt="Screen Shot 2019-09-04 at 5 38 21 PM" src="https://user-images.githubusercontent.com/360826/64294209-3f63c000-cf3c-11e9-8528-524d194b22a4.png">

**Comment by luwes** [comment]
after using `new Set()` https://github.com/luwes/sinuous/commit/7dcd64b41a2e62cb6201366e72355863750310c7 for the listeners/subscribers:

```
One observers many observes one - Started/Updated in 1/42 ms.
500 props observing sibling -  Started/Updated in 1/1 ms.
Late dependency change - Updated in 258ms.
Unused computables -   Updated in 27 ms.
Unused observables -  Updated in 14 ms.
Observable with many observers + dispose - after subscribe: 204ms, after set: 347ms, total: 408ms


Completed performance suite in 0.91 sec.
```

confirms that `observable._listeners.splice(observable._listeners.indexOf(update), 1);` was the bottleneck.

**Comment by luwes** [comment]
Thanks for the feedback all, really appreciate it! Closing this issue as most was covered I think. Opening a new one for the specific run id concept #34

**Comment by ryansolid** [comment]
Given how small the library performance is remarkably close to mobx after latest update. Using cellx bench: https://codesandbox.io/s/cellx-bench-r3i5k

I also confirmed behavior is as expected in all my test scenarios.
