### ISSUE TITLE
Event Handling in Components

### ISSUE THREAD

**Issue by rozek** [luwes/sinuous#218]
It seems that, if one defines a Component

```
  function Component () {
    return html`<div>...</div>`
  }
```

and uses it somewhere else, the user cannot easily provide event handlers

```
  document.body.append(html`
    <${Component} onpointerdown=${(Event) => console.log(Event)}/>
  `)
```

The given handler will never be invoked.

A potential workaround could be to fetch any event handlers as Component properties and provide them explicitly:

```
  function Component (Attributes) {
    return html`<div onpointerdown=${Attributes.onpointerdown}>...</div>`
  }
```

However, this would require every component to support every potential event handler - which would be far from ideal...

Another workaround could be to provide delegated event handlers in `document.body` but that would contradict the component idea...

Is there any better alternative or should we consider this behaviour as a bug?

**Comment by achou11** [comment]
@rozek this seems to be an intentional design choice, as is common in many other component-based rendering libraries. the general idea is that components should expose event handler callbacks explicitly (as seen from your "workaround" solution). 

if you really wanted to avoid passing an explicit attribute/prop, you could probably use event delegation from the consuming component e.g.

```js
function ConsumingComponent () {
  function handlePointerDown (event) {
    // Access to the event via event bubbling
  }
  
  return html`<div onpointerdown=${handlePointerDown}><${Component} /></div>`
}
```

(pardon any syntax errors - I forgot any intricacies around Sinuous' templating)

to my knowledge, Sinuous doesn't do any weird patching or event mangling for native events (e.g. click, pointer, etc), so this _should_ be feasible

**Comment by rozek** [comment]
I understand...

although event delegation would require to add some kind of class or similar discriminator to the actual component in order to filter relevant events (i.e., event targets) only.

...which becomes a bit hacky if you have a `map` of inner components and have to make event handling list item specific

**Comment by achou11** [comment]
I don't think there's anything wrong with that, but yeah maybe not as feasible depending on your use cases. Using data attributes and or classes with event delegation can be quite elegant :)

**Comment by rozek** [comment]
good idea! I completely forgot about data attributes, but you are right, using them would not be "hacky" at all!

Thanks for that suggestion!
