### ISSUE TITLE
Verify  `map` disposers index

### ISSUE THREAD

**Issue by luwes** [luwes/sinuous#23]
Related to https://github.com/luwes/sinuous/commit/62c57338e2d7b28f0b0b3393568cd699deea60bd

**Comment by luwes** [comment]
This was fixed in https://github.com/luwes/sinuous/commit/2104b6788a468845c6b1a6a98d2d2cce2486fea0
Removed es6 Map for older browsers here https://github.com/luwes/sinuous/commit/40933cd6cc24bf7f4a5e424107c7323fbc5432c1

**Comment by leeoniya** [comment]
> Removed es6 Map for older browsers here 40933cd

:-1: 

supporting anything older than IE11 in 2019 is rather silly. even ie11 is basically dead.

ttps://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser_compatibility

**Comment by luwes** [comment]
@leeoniya I agree with you, at the company I work I'm the first requesting to drop support for older browsers but unfortunately IE11 is quite a big browser share in our stats, bigger than Edge and we have a case where some enterprise software is forcing them in IE10 mode by a meta tag. we support that for now 🤦‍♂ 

in the `map` module it was quite easy to get around using `Map`, just a few extra bytes so I thought why not

**Comment by ryansolid** [comment]
That's great. I just don't see you setting the disposer index anywhere except on create.

I see the tests but I'm not sure they will catch the issue. You move stuff around but where you hit problems will be overwrites on the same index. The problem is the overwritten index is never disposed, and other elements that share the index previously can free up the current.

I was going to make a codesandbox but it looks like Sinuous is broken there. I can't get a single one to load due to:
> Could not find module in path: 'sinuous/observable' relative to '/node_modules/sinuous/dist/sinuous.js'

But roughly I think you want a test like this:
```js
  let one = o(1);
  let two = o(2);
  let three = o(3);
  let four = o(4);
  let five = o(5);
  // initialize 1, 2, 3, at indexes 0, 1, 2
  const list = o([one, two, three]);
  const el = h('ul', map(list, item => h('li', item)));
  t.equal(el.innerHTML, lis('1,2,3'));

  // insert 4, 5 at index 0, 1 overwriting disposers[0, 1]
  list([four, five, one, two, three]);
  t.equal(el.innerHTML, lis('4,5,1,2,3'));

  // remove 1, 2, with disposal index 0, 1, freeing disposers[0, 1]
  list([four, five, three]);
  t.equal(el.innerHTML, lis('1,2,3'));

  one(11);
  two(22);
  three(33);
  four(44);
  five(55);

  t.equal(el.innerHTML, lis('44,55,33'));

  t.end();
```
If your fix works this should illustrate it.

**Comment by luwes** [comment]
thanks for saving me again @ryansolid. `map` was indeed broken like you explained, I did find a fix by using a unique counter that would never make the index/key overwrite but I figured it got a little out of hand, and also by the valid feedback from @leeoniya, so I added it in again. 

aah I think I know what the codesandbox issue is, it's because Sinuous has some peer dependencies which are currently defined as `sinuous/observable` for example which don't resolve in the browser. was it with `<script type=module>`?

**Comment by ryansolid** [comment]
Yeah I know this because I used arrays before I moved to Map... there was a time before I added Fragment support that I had taken the stage0 reconciler and updated all the disposers appropriately using an array. My earliest version of fragments worked differently than the marking the groups and that version became difficult to do the swaps. I think it's doable now but I also think it's a bit complex.

The examples I was having issues with sinuous was just added as dependency npm style built with pacel. LIke say this one: https://codesandbox.io/s/sinuous-counter-z6k71. It might be platform specific, but right now on my Mac using Chrome at work I can't seem to load any of the Sinuous examples.

**Comment by luwes** [comment]
great to know, I saw you switched reconcilers in Solid 0.9.0. Does it still support fragments? I didn't see the grouping there.

a little rabbit hole with Codesandbox, fixed here https://github.com/mjackson/unpkg/issues/210

**Comment by ryansolid** [comment]
Oh great. I actually refreshed on one about an hour ago and saw it worked.

Yes I did for features more than anything. I wanted to separate stuff to deal with unexpected issues around the JSX abstraction and Typescript. And to not lock people into the Control Flow anymore. Which means I end up doing reconciliation twice, once in the Reactive System, and once in the DOM renderer. This means more JS work and more code (bundle size feels it a bit). But in so Fragments are just arrays, and arrays nested in arrays all just get normalized. It simplifies stuff greatly, and by some initially unexpected chance ended up being more performant.  It also led to a decision that I needed a mount point. Not everything is just a DOM node anymore. Arrays and Functions are now valid at the entry.

There are a couple issues there I'm dealing with right now so I won't say it's perfect yet. I did a couple things a little lazy figuring they weren't common enough to worry about being unoptimized but they can actually cause infinite loops in the Reactive system. I'm hoping to fix that over the next couple days. It's all fixable at the cost of some more code size. When I clean up a bit more it might be worth looking at. I love the flexibility in general as it opened up all the libraries. Like MobX JSX can now use its mutable observableArray methods and decorators with Classes etc...

**Comment by luwes** [comment]
I recently had a similar issue but ended up customizing the HTM package for Sinuous so it passes arrays and functions at the entry also through the `h` function which can handle any type 😅 

Real interesting about the fragments and arrays. I'll check it out.
