### ISSUE TITLE
Lifecycle method

### ISSUE THREAD

**Issue by kethan** [luwes/sinuous#73]
Is there any lifecycle method like useeffect() or is it possible to use hooks in Swiss for sinuous?

**Comment by luwes** [comment]
Sinuous doesn't have any lifecycle methods at the moment, I haven't really had the need for them but it does make sense in some situations. To keep the core small and lean I can't add them to the core but an extra small module would make sense here.

e.g 
https://github.com/WebReflection/disconnected
https://github.com/ryansolid/solid/issues/36#issuecomment-506189250

Sinuous's equivalent of the React like hooks are the observable computations which re-render a small part of the DOM.

The hooks in Swiss don't work with Sinuous because they require a high level render function. [`sinuous/render`](https://github.com/luwes/sinuous/tree/master/packages/sinuous/render) would work but that module is still pretty experimental. It works in a similar way than lit-html.

**Comment by luwes** [comment]
@kethan I had some time to look into this and ended up creating a small module for it. It was easier said than done to do this in a performant way but I think this should do it. https://github.com/luwes/disco

It works with native DOM events `connected` and `disconnected` so these can be added to any element in Sinuous. `observe(...nodesOrSelectors)` can be called multiple times but best is to keep the scope as narrow as possible for best performance.

(`observe('div')` would be expensive in a large application because it would trigger a connected and disconnected event for all child div's of the removed or added element).

https://codesandbox.io/s/happy-sunset-ge3rw

```js
import { html } from 'sinuous';
import { observe } from '@luwes/disco';

observe('#hustle');
const hustle = html`
	<div id=hustle onconnected=${() => console.log('connected!')} />
`;
document.body.append(hustle);
```
