### ISSUE TITLE
Component state

### ISSUE THREAD

**Issue by mindplay-dk** [luwes/sinuous#74]
Is there any such thing as component state in Sinuous?

For example, let's say I'm building a date-picker drop-down as a component - beyond the application-dependent value (selected date) this also has instance-dependent state, which isn't usually relevant to the application, such as whether the drop-down is currently open, and what month is currently selected in the drop-down.

Such state typically lives and dies with the component instance - if, for example, you were to switch away from a tab with an open date-picker, the user naturally expects this state to reset. "Out of sight, out of mind."

Does Sinuous currently provide any means of maintaining component instance-dependent state, or do we need currently to manually maintain (and reset etc.) such state as application-state?

(Is there any plan to support instance-dependent state?)

**Comment by luwes** [comment]
Thanks for your feedback @mindplay-dk.

A component is not much more than a function in Sinuous so local state are the variables or observables defined in the component function and are not exposed outside the function.

I think it might mean yes, more manual setup and teardown. I'm not sure how it works in other UI libs. Does the component state reset automatically?

In the case the component is removed from the DOM and has to re-run again, the state would also be reset since the component function is called again.

**Comment by mindplay-dk** [comment]
> A component is not much more than a function in Sinuous so local state are the variables or observables defined in the component function and are not exposed outside the function.

Defining observables *inside* a component function is possible?

That might be what I'm looking for - I haven't seen an example of that.

But if you define observables inside a component function, do you get a single shared state for all component instances (as normally) or a distinct state per component instance? (other than in terms of being able to keep state private, is there any difference in terms of the life-cycle of this state?)

> I'm not sure how it works in other UI libs. Does the component state reset automatically?

For the most part, I think, yes. In React, for example, the `useState` hook creates state with a life-cycle that is directly tied to the component instance - it initializes when the component mounts in the DOM, and gets destroyed when it unmounts.

I'm not sure if Sinuous really has an (internal) explicit component instance life-cycle like this?

As I understand it, components only really have a creation phase? they don't really "update" - only the segments that are affected by a state change actually "update"? So there might not be any component "instance" to which state could naturally be attached?

**Comment by luwes** [comment]
yes, that should do it. it will be a distinct state per component instance.

it might be less obvious but every normal function execution has its own state.
most of the times it's not so visible because only one item is returned, the revealing module pattern makes this clearer. it can be very similar to a class instance.

you're right, the creation phase lays everything out and only the fine dynamic parts will get updates down the road. lifecycle methods aren't included out of the box but could be added with mutation observers (#73). I might look into this.

I'll see if I can come up with an example to make it more clear.

**Comment by mindplay-dk** [comment]
> it will be a distinct state per component instance.

@luwes that's amazing! ... Sinuous may have the most elegant, straight-forward state management of any framework I've seen - a single mechanism that covers both application and component state. This is one feature of which other frameworks ought to be green with envy! :laughing: 

Seriously, every other framework I've tried has *either* application state and completely neglects component state, or (the majority) have only component state and requires some other library or entirely different ways of managing application state - context/reducer, Redux or a zillion other libs.

So I think there's a task here as far as updating the docs? I didn't find an example of application vs component state anywhere.

You should consider drumming this up on the home-page as well, as I believe this sets apart Sinuous from most other frameworks in a *really* important way. :smiley:

**Comment by luwes** [comment]
I really appreciate your feedback @mindplay-dk, made my day :) 

Looking how this can be expressed in the documentation, I'm really fond of the state management myself.

Credit really goes to @adamhaile with https://github.com/adamhaile/S
