### ISSUE TITLE
Auto wrap expressions in compiler (no closures needed)

### ISSUE THREAD

**Issue by luwes** [luwes/sinuous#78]
It's possible to auto wrap expressions via `sinuous/babel-plugin-htm`.
A small dev ex plus when using the compiler instead of the runtime.

Wondering if this should be an option?
Negative would be that it leads to inconsistency between runtime and compiled views.

Before:

```js
html`<p>${() => observableCondition() ? 'foo' : 'bar'}</p>`
```

After:

```js
html`<p>${observableCondition() ? 'foo' : 'bar'}</p>`
```

related issue in Surplus, https://github.com/adamhaile/surplus/issues/74

**Comment by heyheyhello** [comment]
Less magic is good to keep things simple. I think it's better to just be honest about needing closures as a fundamental part of the environment we're working in.

One of the huge points of HTM is to not need to have a build step, and now you'd be requiring it else the code won't run as expected in a browser without transpilation. Also, people reading the "After" who know how JS+Sinuous works could be very confused and see it as a mistake

**Comment by ryansolid** [comment]
I didn't comment on it before but with say JSX you could probably do this but with tagged templates I think it might be confusing what is meant for compilation of not. People see it as a runtime solution.

I debated this heavily at the beginning and ultimately because of desire for a React-like experience went all in on proxies and compilation. Also because it was relatively new ground and I thought it could take these approaches to a new place.

But it lead to a lot other decisions. Almost to the point it became a philosophical position since there grew a larger difference between compiled and non-compiled solutions. To the point compiled now has complete preferential treatment on features and API decisions.
