### ISSUE TITLE
Usage with web components?

### ISSUE THREAD

**Issue by davidbwaters** [luwes/sinuous#83]
Hi.  I'm familiar with Swiss and understand it has a sinuous renderer but am interested why this would or wouldn't play well with web components.  Maybe add an example?

I understand solid.js has a lot of features for WCs (like shadow portals) but I like how lean and modular this is and understand this library works similarly.

I'm sure i could get non-shadow custom elements working, but would like to learn more about possible use case for sinuous with WCs.

**Comment by luwes** [comment]
good question @davidbwaters, Swiss and Sinuous definitely can play well together.

it's good to see the difference in what custom elements and most UI libraries bring. I think in most cases a UI library is a hard requirement (unless you'll going to be using the native DOM API's, let's assume that's an edge case)

custom elements are awesome but not essential, come with some overhead because it'll require more code to get the element API interface right. I can't recommend using shadow DOM at the moment because of browser support, but it is an option to use this in Swiss, see https://github.com/luwes/swiss/#elementname-comp-enhancer-options--htmlelement

not sure what the portal provides, is that for CE slots?

**Comment by ryansolid** [comment]
Portals like the [React Portal](https://reactjs.org/docs/portals.html) feature. It's just a trick to support rendering stuff outside of the normal flow. Putting modals inside the flow has several issues (it is doable but there are big limitations). I was frustrated that I couldn't find a single Web Component library with this feature. Especially if you are on the Shadow DOM path. Obviously Shadow DOM is not widely supported from a legacy standpoint (although Edge Chromium marks all major vendors having a solution). I'm not sure Web Components are dynamic enough without Shadow DOM given slotting (ie... the props.children) of the Web Components is pretty core, but that is just a personal opinion. Popular web component libraries seem to be forgoing it. Solid Element also ships with its own ShadyCSS mod to support Shadow CSS when used along with a Shadow DOM polyfill.

That being said Web Components do have an overhead and they put some limitations on the power of these frameworks. So it's a calculated tradeoff. I did work to support Context API with Web Components (linking roots over async connectedCallback element upgrade) but I had to reduce support of Suspense as things got more complicated timing wise. Stuff like SSR comes to mind too. I think working with Web Components right now is a bit wild west and you have to be prepared to get your hands dirty to make your solutions work. Outside of stuff like Stencil or Polymer be prepared to do some plumbing. But then again if its simple enough might just work quite nicely as is.
