### ISSUE TITLE
Discarding `subscribe` return value and safety

### ISSUE THREAD

**Issue by blankhart** [luwes/sinuous#90]
In at least one place the `h` source calls `subscribe` and discards the unsubscribe function it returns.  E.g., [insert](https://github.com/luwes/sinuous/blob/6790d18d353077835974f93c76ecca67c6d4bc58/packages/sinuous/h/src/insert.js#L35).  When is that safe?

**Comment by luwes** [comment]
it's safe when the computation has a parent computation because the parent automatically cleans up its children. it's not so well documented but if you plan to create several standalone Sinuous components and they will be removed from the DOM in the future it's best to wrap them in a `root()` call something like

```js
root(dispose => {
	return html`<div ondisconnected=${dispose}> </div>`;
});
```

when `dispose()` is called when the element is removed from the DOM, it cleans up all the child computations. no need for manually `unsubscribe()`.

keep in mind it's only necessary when the root element of your app will be removed. most of the time I think when you build an app the top level elements app/container stay in the DOM.

hope this helps or makes some sense.

**Comment by blankhart** [comment]
Yes, that is helpful thanks.  Is there a distinction in this regard between having a direct parent versus having a root parent?  Say that under a root, computation A spawns computation B and conditionally C.  C spawns computation D with a subscription to computation B.  Do changes to B cease to propagate to D is A updates such that C is disposed of, or only when the root is disposed of?  I took you to mean when C is disposed of, and the discussion of roots as a separate warning to ensure that in special cases the tree has a parent somewhere.

**Comment by luwes** [comment]
no distinctions, every parent will do the automatic cleanups for its children automatically. so in most you won't need to worry too much about unsubscribing, etc.

Sinuous observable is based on the work of S.js, there's some great docs around the workings https://github.com/adamhaile/S#computations-creating-computations

**Comment by blankhart** [comment]
Understood, thanks for the prompt response.
